FROM centos:8

ARG BUILD_DATE
ARG VCS_REF
ARG BUILD_VERSION

LABEL org.label-schema.maintainer="David.Southwick@cern.ch"
LABEL org.label-schema.build-date=$BUILD_DATE
LABEL org.label-schema.schema-version="1.0"
LABEL org.label-schema.name="davesouth/universalgpu"
LABEL org.label-schema.description="Universal OpenCL base image, with support for Intel CPU+GPU"
LABEL org.label-schema.url="http://docker.io/davesouth/universalgpu"
LABEL org.label-schema.vcs-url="https://github.com/dcsouthwick/furry-umbrella"
LABEL org.label-schema.vcs-ref=$VCS_REF
LABEL org.label-schema.vendor="WSO2"
LABEL org.label-schema.version=$BUILD_VERSION
LABEL org.label-schema.docker.cmd=None

RUN \
    DEPS="redhat-lsb \
        clinfo ocl-icd-devel \
        intel-opencl intel-level-zero-gpu level-zero intel-igc-core intel-igc-opencl intel-gmmlib \
        intel-oneapi-runtime-tbb intel-oneapi-runtime-opencl" && \
    echo -e "[oneAPI] \n\
name=Intel(R) oneAPI repository \n\
baseurl=https://yum.repos.intel.com/oneapi \n\
enabled=1 \n\
gpgcheck=1 \n\
repo_gpgcheck=1 \n\
gpgkey=https://yum.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB" >> /etc/yum.repos.d/oneAPI.repo && \
    dnf install -y -q epel-release dnf-plugins-core && \
    dnf copr enable -y jdanecki/intel-opencl && \
    dnf install -y --enablerepo="powertools" --setopt=tsflags=nodocs $DEPS && \
    dnf -y clean all --enablerepo='*'